name: Docker Check

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Dockerfile linting
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: build docker but don't push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
